name: Deploy Theme to Development Store

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme
    
    - name: Deploy theme to development store
      env:
        SHOPIFY_FLAG_STORE: ${{ secrets.DEV_STORE_URL }}
      run: |
        cd theme
        shopify theme push \
          --store="${SHOPIFY_FLAG_STORE}" \
          --password="${{ secrets.DEV_SHOPIFY_ACCESS_TOKEN }}" \
          --allow-live \
          --force \
          --theme ${{ secrets.DEV_THEME_ID }}